name: Daily Stock ETL Pipeline

on:
  schedule:
    # Lệnh bảo Bot: Chạy lúc 08:15 UTC (Tức 15:15 giờ VN) từ Thứ 2 đến Thứ 6
    - cron: '15 8 * * 1-5'
  workflow_dispatch: # Nút ma thuật: Cho phép bấm chạy bằng tay bất cứ lúc nào để test

jobs:
  run-etl:
    runs-on: ubuntu-latest # Thuê 1 cái máy ảo Linux xịn nhất của GitHub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL Script (Bơm Data lên Neon)
      env:
        # Lấy cái mật khẩu giấu trong két sắt ra đưa cho file Python
        DB_URL: ${{ secrets.DB_URL }}
      run: python etl_pipeline.py
